
networks:
  auction_net:
    driver: bridge

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - auction_net

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - auction_net
  
  user-ms:
    build: ./User_MicroService
    container_name: user-ms
    ports:
      - "9090:9090"
    networks:
      - auction_net
  
  api-ms:
    build: ./ApiGateWay
    container_name: api-ms
    ports:
      - "8080:8080"
    networks:
      - auction_net
